### ISSUE TITLE
Look for `.yaml` file extension by default 

### ISSUE THREAD

**Issue by aaron11496** [eywalker/nvidia-docker-compose#16]
For parity with `docker-compose` (https://docs.docker.com/compose/compose-file/#service-configuration-reference), you should be able to use either `docker-compose.yml` or `docker-compose.yaml` without using `-f`. Version 0.1.3 does not support `.yaml`.

**Comment by eywalker** [comment]
Sounds like a good addition. @aaron11496 if you would implement this and make a PR, I'd be happy to review and merge. Otherwise, I'll implement this when I get around to next round of implementations.
