### ISSUE TITLE
config['services'] does not exist

### ISSUE THREAD

**Issue by davidkell** [eywalker/nvidia-docker-compose#2]
Hi

We tried to run this script with our docker-compose setup.
Here is our error-

```
  File "/usr/local/bin/nvidia-docker-compose", line 34, in <module>
    for service, sconf in config['services'].items():
KeyError: 'services'
```

We tried to go through the steps bit by bit. It does seem our system detects the cuda devices- cuda_config is populated. config looks like just a dict/list representation of the yaml file, so can't see where to add services.

When we try to run nvidia-docker-plugin, we get this error

```
nvidia-docker-plugin | 2016/10/02 16:52:03 Serving plugin API at /run/docker/plugins
nvidia-docker-plugin | 2016/10/02 16:52:03 Serving remote API at localhost:3476
nvidia-docker-plugin | 2016/10/02 16:52:03 Error: listen tcp 127.0.0.1:3476: bind: address already in use
```

Perhaps this is why they do not detect the service?
I saw this post- https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker-plugin
We do have docker and nvidia-docker in the same location as they do- is this what they mean by volume or do I need to point the -d flag somewhere?

We have run single nvidia-docker containers without issue.

Thanks in advance!

**Comment by eywalker** [comment]
Hi @davidkell. Would you mind posting your docker-compose.yml file content here? That'll help a lot with debugging.

**Comment by davidkell** [comment]
Just found the solution! We were using a docker-compose tank convention where we just listed the services. I guess you're expecting docker files like-

```
version: '1'
services:
  X
```

whereas we just had

```
X
```

where x lists the individual services + confit details. Maybe worth checking for this eventuality?

D

**Comment by eywalker** [comment]
Hi @davidkell, I'm following the newer `version: '2'` docker-compose convention which requires the listing of services under `services:` heading. You can find the details here https://docs.docker.com/compose/compose-file/#/version-2. Since `version: '1'` syntax will eventually be not supported, I do not plan on adding compatibility with it. I hope that you are fine converting your config to be version 2 compatible.
