### ISSUE TITLE
Unable to generate with -G

### ISSUE THREAD

**Issue by psychoveter** [eywalker/nvidia-docker-compose#21]
environment: 
python --version
Python 3.6.0 :: Anaconda custom (64-bit)
conda --version
conda 4.3.27
error: 
Traceback (most recent call last):
  File "/home/veter/ide/anaconda3/bin/nvidia-docker-compose", line 84, in <module>
    sconf.setdefault('volumes', []).extend(cuda_config['Volumes'])
AttributeError: 'list' object has no attribute 'setdefault'

Also tried cloning repo and building dist, got the same exception with python 2.7

**Comment by eywalker** [comment]
Hi @psychoveter, this sounds like problem with the particular `docker-compose.yml` file. Can you post the `docker-compose.yml` file so I can have a better idea of what's going on. I'm suspecting that you are placing individual services as list under the `services:` block.

**Comment by eywalker** [comment]
Hey @psychoveter any update on this?

**Comment by eywalker** [comment]
Given that I'm not getting further information to be able to help debug and also because this is likely an issue in the syntax of `docker-compose.yml` file, I'm closing this issue. Feel free to ping back on this if more information can be provided on this.
