### ISSUE TITLE
Nvidia-docker2

### ISSUE THREAD

**Issue by cyberwillis** [eywalker/nvidia-docker-compose#23]
any way to use it with nvidia-docker2 alpha ?

**Comment by cyberwillis** [comment]
My problem was solved!

**Comment by eywalker** [comment]
Hi @cyberwillis, if you figured out a good way to integrate it, would you mind sharing? I'm curious how you resolved this question.

**Comment by cyberwillis** [comment]
Hi again... 
Sorry the delay in get back to you.
At first my problem was that I had a composer file that wasn't building or running by nvidia-docker-compose, but the problem is not nvidia-docker-composer at all, because the nvidia-docker now has changed the way it works with introduction of nvidia-docker 2 alpha.
Now it needs to pass to the docker daemon the argument --runtime=nvidia that tell the daemon to run the specific runtime for NVidia and by this way even docker-compose wasn't able to do things. At least I don't know a way to send runtime arguments to dockerd by docker-compose. 

So investigating a little [here](https://github.com/nvidia/nvidia-container-runtime#daemon-configuration-file), I found that the specific runtime can be set in /etc/docker/daemon.json
<pre>
{
    "default-runtime": "nvidia",
    "runtimes": {
        "nvidia": {
            "path": "/usr/bin/nvidia-container-runtime",
            "runtimeArgs": [ ]
        }
    }
}
</pre>
by using this the docker-compose started to work again, because eliminates the necessity of pass this argument all the time. Probably nvidia-docker-compose will also work now ... I don't get a time to test. I do have a big chain of images to build and run to be sure about this solution.
But apparently its working... I will see at the end.

Also to complement nvidia-docker-plugin does not exist anymore.

[UPDATE] : fixed the syntax of daemon.json

**Comment by cyberwillis** [comment]
Yes I confirm, my problem is solved and I get back on track and docker-compose alone is doing everything now. I am not using nvidia-docker-compose because probably it's trying to do something else involving nvidia-docker-plugin that is not needed anymore.

**Comment by eywalker** [comment]
@cyberwillis thanks a lot for sharing this!

**Comment by anibali** [comment]
It looks like docker-compose will be gaining a "runtime" option for the 2.3 schema next release, which will enable an alternative to setting default-runtime in daemon.json. See https://github.com/docker/compose/pull/5405.

**Comment by FangliangBai** [comment]
Hi @cyberwillis , I followed your solution but couldn't find /etc/docker/daemon.json on my Ubuntu.

I used `pip install nvidia-docker-compose` with build-in python. Do you have any idea?

**Comment by FangliangBai** [comment]
efwef

**Comment by Xin-cqu** [comment]
> Hi again...
> Sorry the delay in get back to you.
> At first my problem was that I had a composer file that wasn't building or running by nvidia-docker-compose, but the problem is not nvidia-docker-composer at all, because the nvidia-docker now has changed the way it works with introduction of nvidia-docker 2 alpha.
> Now it needs to pass to the docker daemon the argument --runtime=nvidia that tell the daemon to run the specific runtime for NVidia and by this way even docker-compose wasn't able to do things. At least I don't know a way to send runtime arguments to dockerd by docker-compose.
> 
> So investigating a little [here](https://github.com/nvidia/nvidia-container-runtime#daemon-configuration-file), I found that the specific runtime can be set in /etc/docker/daemon.json
> 
> {
>     "default-runtime": "nvidia",
>     "runtimes": {
>         "nvidia": {
>             "path": "/usr/bin/nvidia-container-runtime",
>             "runtimeArgs": [ ]
>         }
>     }
> }
> 
> by using this the docker-compose started to work again, because eliminates the necessity of pass this argument all the time. Probably nvidia-docker-compose will also work now ... I don't get a time to test. I do have a big chain of images to build and run to be sure about this solution.
> But apparently its working... I will see at the end.
> 
> Also to complement nvidia-docker-plugin does not exist anymore.
> 
> [UPDATE] : fixed the syntax of daemon.json

That works well for me. Thanks.
