### ISSUE TITLE
Does the project support nvidia-docker version2?

### ISSUE THREAD

**Issue by goodloop** [eywalker/nvidia-docker-compose#24]
reference link:
[nvidia-docker-2](https://aetros.com/blog/Machine%20Learning/14-11-2017-nvidia-docker2-released)

**Comment by arthur-tacca** [comment]
I have a related question: does nvidia-docker version 2 even need nvidia-docker-compose? The linked web page says that it "Doesn't require wrapping the Docker CLI", so maybe the regular docker-compose will work?

**Comment by eywalker** [comment]
Hi @goodloop @arthur-tacca 
As was pointed out by @cyberwillis in #23 , nvidia-docker2 will no longer require nvidia-docker-compose. You can specify the default runtime for Docker to be `nvidia` and this will allow regular `docker-compose` to access GPUs.

**Comment by goodloop** [comment]
sounds great, I will try that.

Sorry that I didn't search issue list first :(

**Comment by eywalker** [comment]
@goodloop No problem - I'll update the README to include a section about `nvidia-docker2` 🙂
