### ISSUE TITLE
Disable gpu support for some services

### ISSUE THREAD

**Issue by MrZoidberg** [eywalker/nvidia-docker-compose#25]
How can I disable GPU support for some services in my docker-compose file while still having one service run with GPU support?

**Comment by eywalker** [comment]
Hi @MrZoidberg sorry I couldn't get back on this earlier. `nvidia-docker-compose` currently does not support disabling GPU support for some services, but this can be added rather straightforwardly - this has been on my todo list (#1) but haven't gotten around implementing it. 

I am open for suggestion on how to best indicate to disable GPU on a service in the docker compose file.

**Comment by MrZoidberg** [comment]
@eywalker cool, thanks! I think using labels to disable/enable GPU should be straightforward

**Comment by eywalker** [comment]
Thinking further about this, I'm thinking that it is probably most intuitive to simply accept a `nvidia-docker-compose` specific setting called `enable_cuda`. You can set this to `false` to turn off GPU support for the specific service: e.g.

```yaml
version: '3'
services:
  my_non_gpu_service:
    build: .
    enable_cuda: false
```
To stay compatible with previous versions, `enable_cuda` defaults to `true` and thus will mount all availavle GPUs unless you limit using `/dev/nvidiaX` under devices.

I'll play around a bit with other implementations before committing to this solution though.

**Comment by eywalker** [comment]
@MrZoidberg `enable_cuda` feature is now implemented in "beta" state, but is made available in the latest version of `nvidia-docker-compose`. Once I have a chance to test it further and verify that it works fully, I will document this feature.
