### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by magick93** [eywalker/nvidia-docker-compose#26]
Hello

I am getting an error similar to that described on https://github.com/eywalker/nvidia-docker-compose/issues/22

I see that nvidia-docker v2 is not supported. Is that still the case? How can I tell what version I have?

When I run `nvidia-docker --version` I get `Docker version 17.12.1-ce, build 7390fc6`. I'm guessing this is not actually the nividia-docker version.

Thanks

**Comment by eywalker** [comment]
Try running `nvidia-docker version`

**Comment by magick93** [comment]
Ah ha!

```
NVIDIA Docker: 2.0.3
Client:
 Version:	17.12.1-ce
 API version:	1.35
 Go version:	go1.9.4
 Git commit:	7390fc6
 Built:	Tue Feb 27 22:17:40 2018
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.1-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	7390fc6
  Built:	Tue Feb 27 22:16:13 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by eywalker** [comment]
Indeed `nvidia-docker` v2.0 is still not supported by `nvidia-docker-compose`. I do plan on looking into how to best integrate with v2.0 as I would still like to be able to do things like auto-launching as many containers as the number of GPUs and distributing them. However, as far as just getting `docker-compose` to work with CUDA enabled containers, you can refer to the issue #23 on how to achieve that.

**Comment by aminought** [comment]
nvidia-docker 1.0.1 not working too.

```
NVIDIA Docker: 1.0.1

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by eywalker** [comment]
@aminought I'll need the error output or some additional information to debug this. Also, please verify that `nvidia-docker` is working by itself. Quick tests like `nvidia-docker run --rm nvidia/cuda nvidia-smi` would be a good one.

**Comment by andremoeller** [comment]
@aminought fwiw, i'm successfully using nvidia-docker 1.0.1 with nvidia-docker-compose

NVIDIA Docker: 1.0.1

Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:01 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:31 2018
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by eywalker** [comment]
As far as I'm aware `nvidia-docker-compose` works on nvidia-docker 1.0.1, and opening question was successfully resolved, so I'm closing the issue. @aminought if you have more specific issues, feel free to open a separate issue and we can discuss it there.
