### ISSUE TITLE
Missing docker-compose file.

### ISSUE THREAD

**Issue by craigrmann** [eywalker/nvidia-docker-compose#28]
I am attempting to use PyCharm w/ nvidia-docker-compose set up as my remote project interpreter.

I am getting the message in the title of this post and am wondering what I need to do to correctly get all this sorted.

Thanks for any help you all can provide.

**Comment by craigrmann** [comment]
I think I figured it out. I didn't realize that this was a wrapper for docker-compose.  Makes perfect sense now... going to try to figure it out, will mark closed if I figure it out.

I might suggest referring out to the documentation on how to get started with docker-compose in your readme.md for people as new to this as me. We will see!

**Comment by diegoferigo** [comment]
@creeeeeg This repository might be considered as legacy imo. With `nvidia-docker` 2 you can use the upstream `docker-compose` with the `runtime=nvidia` element. After its recent support of opengl I think it is overly complicated sticking with the former volumes-based method.

**Comment by eywalker** [comment]
@creeeeeg Did you end up figuring the issues out? As @diegoferigo mentioned, `nvidia-docker-compose` is not up to date with `nvidia-docker2`, and use of `runtime=nvidia` in `docker-compose` will enable launching Docker containers with GPU access. There are some functionalities that made it into `nvidia-docker-compose` that I'd be interested in continuing to use (e.g. launching as many containers as the number of GPUs, limiting each container's access to specific GPU etc) but this may be more appropriate as a distinct wrapper around `docker-compose` running with `nvidia-docker2`.
