### ISSUE TITLE
Jinja2 missing from install_requires in setup.py

### ISSUE THREAD

**Issue by arthur-tacca** [eywalker/nvidia-docker-compose#6]
As the title says, Jinja2 should be listed as a dependency so that it is automatically installed when typing `pip install nvidia-docker-compose`. Thanks!

**Comment by pigiuz** [comment]
same issue here
pip install jinja2 solves the issue

**Comment by eywalker** [comment]
Hi @arthur-tacca and @pigiuz, thanks for pointing this out! I've fixed this and have incremented to version `v0.0.5`.

**Comment by pigiuz** [comment]
@eywalker fantastic! thanks!
