### ISSUE TITLE
Error message when docker-compose file could not be found

### ISSUE THREAD

**Issue by ShuangLiBCM** [eywalker/nvidia-docker-compose#8]
The error message is not clear when trying to use docker-compose at a sub folder.

**Comment by eywalker** [comment]
@ShuangLiBCM Thanks for submitting this as an issue. Yes, indeed the returned error message (which is just an error stack from Python) is not helpful or friendly to the user.

**Comment by eywalker** [comment]
Fixed in latest release 0.1.4
